services:
  nestjs:
    build: .
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: npm run start
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nestjs"
    ports:
      - 27017:27017
    volumes:
      - ./.mongo:/data/db
